### ISSUE TITLE
I cant run .sh file

### ISSUE THREAD

**Issue by ramanbharathiya** [MarcinGrabowski/binance-copy-bot#2]
Hello i have done the things as it is which are said by you but i cant able to run the .sh files,please give your mail id or whatsapp or telegram so that i can contact you.

**Comment by MarcinGrabowski** [comment]
Sometimes you need to change permissions on .sh files.
In terminal execute: chmod 755 *.sh

**Comment by ramanbharathiya** [comment]
ok could you please give me your mail address

**Comment by ramanbharathiya** [comment]
![image](https://user-images.githubusercontent.com/124690439/217295173-f20a98df-356d-49ba-9015-5262907aaf2e.png)
please see the image,i am getting like this

**Comment by ramanbharathiya** [comment]
![image](https://user-images.githubusercontent.com/124690439/217295941-7a962c59-d6a4-4c49-8fbd-460b9b08e860.png)

**Comment by MarcinGrabowski** [comment]
if you have windows only write in git bash with dot: ./run.sh

**Comment by ramanbharathiya** [comment]
ok

**Comment by ramanbharathiya** [comment]
![image](https://user-images.githubusercontent.com/124690439/217297805-a5116dd6-c2a0-40f3-887b-3f07fb7218a4.png)
getting error like this

**Comment by ramanbharathiya** [comment]
what i should give here ??
![image](https://user-images.githubusercontent.com/124690439/217298151-0d679e72-473d-4bd9-a836-866b42b0a85e.png)

**Comment by ramanbharathiya** [comment]
could you please give me your mail address

**Comment by MarcinGrabowski** [comment]
![image](https://user-images.githubusercontent.com/13447756/217299221-60b1df9b-022c-4d34-b5b0-59f0112ad4b6.png)

**Comment by ramanbharathiya** [comment]
![image](https://user-images.githubusercontent.com/124690439/217301043-9ce68674-4fb6-471a-9d21-7912b13ca751.png)
getting like this

**Comment by ramanbharathiya** [comment]
please give your mail or telegram please

**Comment by MarcinGrabowski** [comment]
only DC: https://discord.gg/uyEuzF96
