### ISSUE TITLE
code":-1102,"msg":"Mandatory parameter 'quantity' was not sent, was empty\/null, or malformed.","_method

### ISSUE THREAD

**Issue by deepc0re** [MarcinGrabowski/binance-copy-bot#4]
{"code":-1102,"msg":"Mandatory parameter 'quantity' was not sent, was empty\/null, or malformed.","_method":"POST","_url":"https:\/\/fapi.binance.com\/fapi\/v1\/order?timestamp=1676053499000&symbol=GRTUSDT&positionSide=SHORT&side=SELL&type=MARKET&quantity=-0","_httpcode":400}

**Comment by MarcinGrabowski** [comment]
too low depo or percentPerPosition
